### ISSUE TITLE
foutafhandeling splitter

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#103]
Als kolom ontbreekt in model_settings is de foutafhandeling nog niet helemaal soepel. Moet zelf op zoek in de python errors, maar ik mag wel gewoon door met uploaden.

- [x] fouten afvangen en toevoegen naar inforatiescherm en upload mag dan niet op actief. 

![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/f397d228-5a0c-4848-9793-0d7036cbf6cf)

_Originally posted by @wvangerwen in https://github.com/threedi/hhnk-threedi-plugin/issues/94#issuecomment-1739099173_

**Comment by wvangerwen** [comment]
Oplossing:
outputmap leegmaken bij splitten
uitzoeken waarom beiden bijgewerkt

reproductie:
model splitten
sqilte hernoemen/ kopie
model splitten
2 sqlites in outputmap.

**Comment by d2hydro** [comment]
Dit is nu het resultaat in #125:

![Image](https://github.com/threedi/hhnk-threedi-plugin/assets/43996424/a6be917c-8c34-4eee-9d69-ee7aafd2548a)
