### ISSUE TITLE
grid genereren vanuit 3Di grid from schematiszation processing tool

### ISSUE THREAD

**Issue by d2hydro** [threedi/hhnk-threedi-plugin#104]
Voor het grid-genereren gaan we gebruik maken van de 3Di grid from schematisation processing tool

Deze wordt aangeroepen onder laad lagen -> Grid genereren

![Image](https://github.com/threedi/hhnk-threedi-plugin/assets/43996424/9d8b6a68-6291-426a-aa47-ca3f394f8825)

Labels: **Laad lagen**, **taken** , **processing tools**

**Comment by wvangerwen** [comment]
added in #106
