### ISSUE TITLE
Installatie van de plugin & de 3Di modeller interface

### ISSUE THREAD

**Issue by Ckerklaan** [threedi/hhnk-threedi-plugin#11]
De huidige installatie is met een verouderde versie van qgis en qgis installer. Het is doel is om naar de modeller interface te werken en de plugin te kunnen downloaden vanaf de officiele repo van qgis.

 Problemen die er nu nog zijn:

Geopandas is afhankelijk van Shapely en daarmee Fiona. 
- Fiona is een moeilijke install aangezien het gdal wil aanpassen.
- Je kan een wheel gebruiken, maar dit is niet mogelijk met de huidige versie van de modeller interface (windows, qgis=3.16, python=3.7) maar de wheels zijn niet beschikbaar via https://www.lfd.uci.edu/~gohlke/pythonlibs/ voor fiona 1.8.18 en python 3.7.
- Dus, je hebt dan een wheel met Fiona 1.8.19 voor python 3.7 nodig, maar deze heeft gdal 3.2.3 nodig en die kunnen we niet updaten in qgis.
- Via de verouderde installer is fiona en daarmee geopandas wel netjes te installeren. Maar aangezien we de functionaliteiten willen van de modeller interface is dit dus niet ideaal.

Wensen:
- Een hogere versie van gdal zou dit dus oplossen in de nieuwste installatie van de modeller interface. 
- Maar heeft liefst zou gepandas voorgeinstalleerd zijn in de modeller interface.

Zodat we hem niet kwijt raken:
[Fiona-1.8.19-cp37-cp37m-win_amd64.zip](https://github.com/threedi/hhnk-threedi-plugin/files/7692353/Fiona-1.8.19-cp37-cp37m-win_amd64.zip)

De modeller interface wordt gereleased in februari 2022 met hoogstwaarschijnlijk python 3.9 en gdal 3.3.

**Comment by wvangerwen** [comment]
Werkt met modeller interface
