### ISSUE TITLE
Waterdiepte en waterlevels rasters aanmaken.

### ISSUE THREAD

**Issue by Ckerklaan** [threedi/hhnk-threedi-plugin#14]
1. Rasters aanmaken via threedidepth
2. Volumeverschil grid en rasters
3. Input rasters manipuleren om 10 m waterstand weg te halen.
Beginnen met notebook.

**Comment by Ckerklaan** [comment]
Inmiddels een notebook beschikbaar. Volume verschil moet nog.

**Comment by wvangerwen** [comment]
Beschikbaar vanaf [0ae9776](https://github.com/threedi/hhnk-threedi-tools/commit/0ae9776887ef7f3f8f6f428b90c9e6d032e90dc6)
