### ISSUE TITLE
2_e_g_klimaatsommen

### ISSUE THREAD

**Issue by bvanlier** [threedi/hhnk-threedi-plugin#145]

**Comment by wvangerwen** [comment]
@bvanlier hoi Bart, je maakt veel issues aan waar alleen een titel in staat. Zou je deze allemaal samen kunnen voegen in 1 issue en er een werklijstje van maken? dit doe je door `- [ ]` ervoor te zetten

- [ ] 2_e_g_klimaatsommen 
- [ ] 4_b_overzicht_plugin

**Comment by bvanlier** [comment]
@wvangerwen Hoi Wietse, ik denk dat ik het vooral niet zo handig aan het doen ben dan. Jelle had een werk lijst gemaakt voor de plugin en daar had hij de HHNK plugin als 'issue' aan toegekend. Ik heb dat dus ook gedaan voor alle subonderdelen waar de handleiding van de plugin uit bestaat. Volgens mij kan het ook gewoon zonder een issue daaraan toe te kennen ;). Ik zit aan het eind van de week met Jelle en zal dan nog even vragen wat handig is, want ik ga ervan uit dat jullie 'issues' als daadwerkelijk issue behandelen en dat is het in de gevallen van mij niet.

**Comment by wvanesse** [comment]
2_e/g welke file gaat dit nu over?
2/g/1 is niet af bij mij.

**Comment by wvanesse** [comment]
Onder 3 g zie ik iets nieuws. Ku je daar nog toevoegen wat over de statistiek staat in de memo van HKV?
