### ISSUE TITLE
naverwerking dem uit basis halen?

### ISSUE THREAD

**Issue by wvanesse** [threedi/hhnk-threedi-plugin#159]
Waarom niet de dem voor de naverwerking uit de de basis schematisatie map halen? Ik had mijn medel settings titels aangepast omdat het een integraal model, en dan kan het script de dem niet vinden. Nu ben ik blij dat ik dat heb gedaan, want ik wil niet dat hij de dem uit het model gebruikt, daar zijn de panden namelijk uit gehaald. Maar zie niet in waarom niet gewoon één dem uit de basis of zelfs dat je zelf een dem kunt/moet kiezen.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 20
     18 # Set dem path
     19 folder.model.set_modelsplitter_paths()
---> 20 dem = folder.model.schema_1d2d_ggg.rasters.dem
     22 # Set Dem path if its not found
     23 # dem_path_dropdown = widgets.Dropdown(
     24 #     options="",

**Comment by wvanesse** [comment]
dit werkte pas weer toen in en mapnamen en de ettings xls had aangepast. Dus hij leest het wel uit de settings maar doet er niet mee?

**Comment by wvangerwen** [comment]
zie dat Daniel er ook al eea aan heeft gedaan in https://github.com/threedi/hhnk-threedi-tools/pull/85/files. Zal bij het reviewen nog even goed naar kijken.
