### ISSUE TITLE
Bank levels dont need netcdf anymore

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#17]
- [x] change input of function
- [ ] update UI
- [ ] refactor code

**Comment by Ckerklaan** [comment]
@wvangerwen 

Probleempje in de functie 'new_cross_loc_bank_levels' op regel 647. Lijkt erop dat er een geometrie kolom met lijnen wordt vervangen door een met nodes.  Maar we missen nu de kolom met nodes. Snap jij hoe dit komt.?
