### ISSUE TITLE
Droge beddingen

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#19]
- [ ] heel verhaal, staan aanbevelingen op de mail. Vraag Wietse.

**Comment by wvangerwen** [comment]
Hey @jkaptein I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/hhnk-threedi-scripting-60c8ef944a5ad90016daf9d0/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by d2hydro** [comment]
Zie #85
