### ISSUE TITLE
Installatie + documentatie doorlopen + verbeteren

### ISSUE THREAD

**Issue by d2hydro** [threedi/hhnk-threedi-plugin#38]
**Idee installatie:**
- MI downloaden en installeren: https://docs.3di.live/f_3di_instruments_and_downloads.html#di-instruments-and-downloads

- QGIS opstarten, afsluiten, opstarten om 3Di plugin werkend te krijgen.

- HHNK-plugin downloaden (https://github.com/threedi/hhnk-threedi-plugin) en dan de map hhnk_threedi_plugin (dus niet _main) in je appdata zetten;

-  %appdata%\Roaming\3Di\QGIS3\profiles\default\python\plugins\hhnk_threedi_plugin

- Local_settings_default.py naar local_settings.py hernoemen.

- Qgis afsluiten, opstarten om hhnk plugin te installeren (aanvinken in plugins qgis)

**Procedure doorlopen, code + handleiding verbeteren:**

Updaten depencies.py
- [x] aanmaken van een environment.yml met de dependencies (python-versie, packages+versies) voor de hhnk_threedi_plugin.
- [x] evalueren welke packages ontbreken en welke packages een verkeerd versienummer hebben
- [x] bij verkeerde versienummers een melding geven + mogelijkheid dit te negeren
- [x] alle ontbrekende packages installeren, jupyter-notebook in user, de rest in external-dependencies

Deployment toevoegen:
- [x] deploy-plugin script toevoegen voor plugin

Documentatie uitwerken:
- [x] installeren MI
- [x] installeren hhnk_threedi_plugin (via zip-file)

Kijken of we dit kunnen verbeteren: https://github.com/threedi/hhnk-threedi-plugin/issues/38#issuecomment-1447881974

**Comment by d2hydro** [comment]
1. kijk welke versies van pakketten hier geïnstalleerd zijn: c:\Program Files\3DiModellerInterface 3.22\apps\Python39\Lib\site-packages\
2. kijk in c:\Users\XXXX\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\dependencies.py DEPENDENCIES
3. kijk welke versies van pakketten hier geïnstalleerd zijn: kijk in c:\Users\XXXX\AppData\Roaming\Python\Python39\site-packages\

Verifieer of c:\Users\danie\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\hhnk_threedi_plugin\wheels\requirements.txt

**Comment by wvangerwen** [comment]
Andere python environments werken niet meer direct door de plugin installatie. Dit komt omdat we in "C:\Users\wvangerwen\.ipython\profile_default\ipython_config.py" dependencies toevoegen. Dit bestand wordt gedeeld met andere envs. 

Onderaan dit bestand komt bijvoorbeeld dit te staan.

```
c.InteractiveShellApp.exec_lines = ['import sys; sys.path.insert(0,"C:/Users/wvangerwen/AppData/Roaming/3Di/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps"); sys.path.insert(0,"C:/Users/wvangerwen/AppData/Roaming/3Di/QGIS3/profiles/default/python/plugins/hhnk_threedi_plugin/external-dependencies"); sys.path.insert(0,"E:/github/wvangerwen/hhnk-threedi-tools"); sys.path.insert(0,"E:/github/wvangerwen/hhnk-research-tools")']
```

Huidige oplossing om bovenaan alle scripts die andere env gebruiken deze dingen weer weg te halen. 

```
import sys, os
from pathlib import Path

def fix_syspath(verbose=False):
    r"""remove path things that are added in C:\Users\wvangerwen\.ipython\profile_default\ipython_config.py"""
    syspath=sys.path.copy()
    syspathlib = [Path(j) for j in syspath]
    for ii, i in enumerate(['E:/github/wvangerwen/hhnk-threedi-tools',
            os.path.join(os.getenv("APPDATA"), r"3Di/QGIS3/profiles/default/python/plugins/hhnk_threedi_plugin/external-dependencies"),
            os.path.join(os.getenv("APPDATA"), r"3Di/QGIS3/profiles/default/python/plugins/ThreeDiToolbox/deps"),
            os.path.join(os.getenv("APPDATA"), r"\\Python\\Python39\\site-packages")]):
        
        if Path(i) in syspathlib:
            index = syspathlib.index(Path(i))
            sys.path.remove(syspath[index])
            if verbose:
                print(f"remove {syspath[index]}")
        else:
            if verbose:
                print(f"error {Path(i)}")
```

**Comment by d2hydro** [comment]
foutje in c:\Users\XXXX\AppData\Roaming\3Di\QGIS3\profiles\default\python\plugins\ThreeDiToolbox\deps\threedigrid_builder\__init__.py?

![Image](https://user-images.githubusercontent.com/43996424/221864587-1c140103-a498-44cb-96d6-3fab217608e5.png)

**Comment by d2hydro** [comment]
uitrollen bij users:
1. M.I. installeren met juiste versie
2. vanuit admin-user een lijst met toolboxen kopiëren
3. een dictionary met ignored files

**Comment by d2hydro** [comment]
See new user docs

![Image](https://user-images.githubusercontent.com/43996424/227580230-e966622e-124d-4e17-bb35-e0b0983aecd2.png)

**Comment by d2hydro** [comment]
Plugin kan nu gedownloade worden via: https://github.com/threedi/hhnk-threedi-plugin/releases/tag/v0.3.1

**Comment by d2hydro** [comment]
Documentatie wordt nu automatisch gegenereerd @ release: https://threedi.github.io/hhnk-threedi-plugin/
