### ISSUE TITLE
inconsistente packages in locale python39

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#46]
![image](https://user-images.githubusercontent.com/41104904/230602180-2ea70d7b-23c5-4672-8d6f-22731540a512.png)

Melding van inconsistente packages omdat er packages in %appdata%\Python\Python39\site-packages staan. 

Toevoegen als mogelijke oplossing om deze map leeg te gooien?

**Comment by wvangerwen** [comment]
Is het ook mogelijk om het pad aan te geven waar deze packages gevonden zijn? attrs==22.1.0 stond in  %appdata%\Python\Python39\site-packages. 
Vervolgens een melding dat attrs==20.2.0 niet goed is. 
Die staat in C:\Program Files\3DiModellerInterface 3.22\apps\Python39\Lib\site-packages.

Waarom geven we in onze environment.yml het exacte versienummer mee? Dit gaat bij elke update voor meldingen zorgen terwijl het functioneel niet heel veel anders is. attrs>=20.2.0 zou toch ook volstaan.

**Comment by d2hydro** [comment]
Hier even een korte afstemming aan weiden? Exacte versienummers, want een zo gegarandeerd mogelijk werken van de plugin (mits we (goed) genoeg testen). Ook bij nw versies van packages kan functionaliteit breken. En ook, de code begrijpt andere signs dan == nu niet, dus dat zou doorontwikkeling zijn :-).

Al het commentaar lezende denk ik aan de volgende enhancements:
- weergeven van de paden van de conflicterende packages
- optie om (alle?) mismatchende packages te deinstalleren
- optie om pytest te draaien in de environment (zorgen dat we alle tests ín de plugin (kunnen) zetten)
- optie om de melding in de toekomst te negeren (overschrijven van de environment.yml)

**Comment by d2hydro** [comment]
Zoals besproken, je kunt nu naar de packages toe d.m.v. clickable links, zie hieronder ter inspiratie.

![Image](https://user-images.githubusercontent.com/43996424/232772783-80c4e6ee-53c2-4ae7-958e-734c64c6f46e.png)
