### ISSUE TITLE
overzicht gebieden modelbuilder

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#49]
http://srvota155:5000/ heeft overzicht gebieden. Deze (via de documentatie?) ook beschikbaar maken in tabje plugin.
Makkelijkste misschien linkje alleen naar deze pagina. 

- [ ] In documentatie opnemen.

**Comment by d2hydro** [comment]
Zie: https://threedi.github.io/hhnk-threedi-plugin/md_files/polder_clusters/

**Comment by wvangerwen** [comment]
Toegevoegd in #125
