### ISSUE TITLE
migrate sqlite

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#69]
migeren sqlite als die niet bij is met de laatste versie. 

Controle en mogelijke migratie bij inladen lagen.

**Comment by wvangerwen** [comment]
@d2hydro zou je mee kunnen kijken of dit nu een handige opzet is? Een probleem nu nog is dat er een filelock komt op de sqlite door migratie. Hier werk ik omheen door een backup te maken, hier de migratie op te doen en deze terug te kopieren.
Maar de backup kan je dan niet direct verwijderen. 

Hierdoor wordt een map hhnk-threedi-tools\tests\data\_backup steeds groter. Kunnen we deze legen op een andere manier? Misschien bij begin van test

r[#ff7a795d268a7d17c42c4798099fa1cc0368e99a
](https://github.com/threedi/hhnk-threedi-tools/commit/ff7a795d268a7d17c42c4798099fa1cc0368e99a)

**Comment by d2hydro** [comment]
Helaas wordt de database gelockt in bij het executen van sessies op de database, bijvoorbeeld hier: https://github.com/nens/threedi-schema/blob/a667a0178d44dce572b2655c310921e7a67aa2f1/threedi_schema/application/threedi_database.py#L153. Geprobeerd:
- session.commit(), session.close(), idem voor de resultante van session.execute(..).
- session = None, r = None.

Lijkt me dieper te zitten bij de get_session() method van ThreediDatabase of iets dergelijks.

i.i.g. is de enige oplossing voor ons nu te accepteren dat de sqlites gelocked blijven totdat de python-sessie wordt afgesloten.
