### ISSUE TITLE
Openen plugin maakt qgis verticaal groter dan scherm

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#81]
Voor:
![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/fc6c368a-fc9a-43a4-b95a-01ae999f43d8)

Na:
![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/d2abf3fd-120d-4a34-a58d-d576990442e5)

Dit gebeurt alleen als bij het reloaden de vorige versie van de plugin niet sluit. 
Als je de vorige plugin dockwidget afsluit voordat je een (gereloade) start door te klikken op ![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/7508f9a0-5746-405b-8b30-c9ab1bf17da9) dan gaat het wel goed.

Misschien in die richting kijken? Uitzoeken waarom reloaden soms de plugin niet afsluit.

**Comment by d2hydro** [comment]
Aangepast in dockwidget in #106

**Comment by wvangerwen** [comment]
Het is bij mij nog steeds niet gefixed, blijft spelen. Weet niet of we hier een oplossing voor gaan vinden.

**Comment by wvangerwen** [comment]
Mogelijke fix in #146 

toevoegen aan hhnk_toolbox.py -> onClosePlugin()
```
        self.dockwidget.close()
        self.dockwidget = None
```
