### ISSUE TITLE
generate_themes crashes qgis

### ISSUE THREAD

**Issue by wvangerwen** [threedi/hhnk-threedi-plugin#91]
Running sqlite test without loading the porject layers first will crash qgis.

It will run project.generate_themes(). Which will very slowly come to the conclusion it does not have the correct layers available.

![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/85626de5-ea06-4c49-b12f-6275f7f1d3a4)

**Comment by wvangerwen** [comment]
Kan bovenstaande error niet meer reproduceren, maar het blijft vastlopen. Heeft waarschijnlijk niets met generate_themes te maken want die staat momenteel uit in mijn branch.

Crash reproduceren door:
De sqlite_check draaien in een nieuwe qgis

werkt NIET als de pythonconsole open is, QGIS blijft hangen:
![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/46c237e1-fa08-433e-b118-c9892e0aad87)


werkt wel als de pythonconsole gesloten is.

**Comment by wvangerwen** [comment]
Bij het openen van de console nadat de taken zijn gestart komt er een enorme hoeveelheid fouten in de console. Hebben we debug logging verkeerd aanstaan of moet er iets met gdf_write_to_geopackage gebeuren.

![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/f8996de6-3326-4f13-a9f4-c08d8cc36415)

**Comment by d2hydro** [comment]
In de main-branch:
1. open MI
2. laad test-model
3. open python-console(!)
4. voer SQL tests uit

QGis blijft hangen. Wanneer Python-console niet open staat, crashed QGIS niet.

**Comment by d2hydro** [comment]
Wat overblijft is een logging-ussue, zie #128
