### ISSUE TITLE
model splitter - verbeteringen

### ISSUE THREAD

**Issue by wvanesse** [threedi/hhnk-threedi-plugin#94]
Mede n.a.v. de opmerkingen de volgende voorstellen voor verbeteringen bovenop #93. Ik ga ervan uit dat de splitter niet gesloten wordt wanneer een run of upload bezig is:
- [x] `Cancel` vervangen voor `Close` welke `Enabled`, `Disabled` en `Information` leeggooit en de widget sluit
- [x] `Enabled`  en `Disabled` list-widgets opnieuw populaten met de inhoud van settings_df (de excel) bij start van de model splitter
- [x] `Upload modelversion(s)` en `Close` disablen wanneer run draait en `Run: Model Splitter` en `Close` disablen wanneer upload draait
- [x] zorgen dat alle knoppen juist disabled/enabled zijn wanneer je geen/wel model hebt geselecteerd
- [x] `model_settings; als ``kmax`, `grid_space`, `output_timestep` vergelijken en waarschuwen wanneer deze niet consistent zijn voor alle modellen
- [x] close-button enablen bij Exception
- [x] Upload modelversion(s) enablen wanneer commit message niet leeg is
- [x] inhound \hhnk-threedi-tools\tests\data\model_test\02_schematisation\model_settings.xlsx syncen met \hhnk-threedi-tools\hhnk_threedi_tools\resources\model_settings.xlsx
- [x] starten met een volle disabled_list en een lege enabled_list
- [ ] hoofdletters en punten toestaan in comment

de modelsplitter laat namen van modellen in enasbled/disabled van het vorige model staan. Ik heb van 1 model de modellen gesplit. Daarna naar een 2e model gewisseld en nu staan de namen van dit model nog in de lijstjes.

Dus nhflo_wghg staan niet in de excel van //corp.hhnk.nl/data/Hydrologen_data/Data/02.modellen/HKC23010_Eijerland_ZP/02_schematisation/model_settings.xlsx

maar zie ik nu wel. 

![image](https://github.com/threedi/hhnk-threedi-plugin/assets/48908991/db4dea30-4f6f-4e1e-81c3-d8f38d1c7e02)

Ik disable de wgxg modellen en ga verder met upload, maar deze zijn uiteindelijk toch gebruikt als naam voor de zgxg modellen niet. Achter de schermen lijkt dus van alles door elkaar te gaan.

**Comment by wvanesse** [comment]
zoals je hierboven ziet blijft het knopje upload modelversions ook 'ingedrukt'

**Comment by jkaptein** [comment]
> zoals je hierboven ziet blijft het knopje upload modelversions ook 'ingedrukt'

Hij gaat weer op disbabled zodra je het model upload, zo moet je het model dus weer opnieuw splitten voor je weer kan uploaden!

**Comment by d2hydro** [comment]
linkt aan https://github.com/threedi/hhnk-threedi-tools/issues/60

**Comment by wvangerwen** [comment]
Als kolom ontbreekt in model_settings is de foutafhandeling nog niet helemaal soepel. Moet zelf op zoek in de python errors, maar ik mag wel gewoon door met uploaden.

@d2hydro kan je deze fouten afvangen en toevoegen naar inforatiescherm en upload mag dan niet op actief. 

![image](https://github.com/threedi/hhnk-threedi-plugin/assets/41104904/f397d228-5a0c-4848-9793-0d7036cbf6cf)
